baseURL = "/"
languageCode = "en-us"
title = "de1ux"
theme = ["hugo-video", "xmin"]

pygmentsUseClasses=true

[params]
    footer = "Send me [an email](mailto:nathan@de1ux.com), sign up on [the mailing list](http://eepurl.com/hio_5z), or [subscribe to RSS](index.xml) to get notified of new posts!"